name: ac_webview
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  autocode:
    path: './../autocode'
  flutter_inappwebview: ^6.1.5
#  flutter_inappwebview: ^6.2.0-beta.3
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.4.0
  webview_win_floating: ^3.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
