name: ac_printing
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  autocode:
    path: './../autocode'
  ac_extensions:
    path: './../ac_extensions'
  ac_mirrors:
    path: './../ac_mirrors'
  pdf: ^3.11.3
  printing: ^5.14.2
  puppeteer: ^3.18.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
